### ISSUE TITLE
Convert to EPUB

### ISSUE THREAD

**Issue by gingerbeardman** [gingerbeardman/iwata-asks-downloader#2]
Output may need tidying, currently pandoc throws some errors

**Comment by Strife89** [comment]
Such a feature would be awesome! Hope that you can make it happen.

**Comment by gingerbeardman** [comment]
Should happen soon

**Comment by gingerbeardman** [comment]
Individual ePub generation is now available @Strife89

Next, to merge them with ordered chapters.
